joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  # in Hz

TorqueController:
    type: effort_controllers/JointGroupEffortController
    joints:
        - iiwa_joint_1
        - iiwa_joint_2
        - iiwa_joint_3
        - iiwa_joint_4
        - iiwa_joint_5
        - iiwa_joint_6
        - iiwa_joint_7

