service:
  robot_description: /iiwa7_description
  end_effector: iiwa_link_ee
  fk_service_name: iiwa_fk_server
  ik_service_name: iiwa_ik_server
  jacobian_service_name: iiwa_jacobian_server
  jacobian_deriv_service_name: iiwa_jacobian_deriv_server
  jacobians_service_name: iiwa_jacobians_server
  gravity_service_name: iiwa_gravity_server
